# **Latar Belakang**

Dalam bisnis restoran, data transaksi penjualan merupakan sumber informasi penting yang dapat digunakan untuk mengevaluasi kinerja bisnis dan mendukung pengambilan keputusan. Manajemen membutuhkan laporan yang mampu memberikan gambaran mengenai pendapatan, produk terlaris, pola pembelian pelanggan, serta tren penjualan yang terjadi.

SQL digunakan untuk mengolah dan menganalisis data transaksi agar menghasilkan informasi yang relevan dan mudah dipahami oleh manajemen. Melalui dataset Pizza Transaction, analisis dilakukan untuk mengidentifikasi performa penjualan, mengetahui produk yang paling diminati, serta menemukan peluang peningkatan bisnis berdasarkan data yang tersedia.

<img src="https://i.pinimg.com/originals/3f/16/66/3f1666fa70ae1e30b0b5b4c862c363aa.gif" width="30%">
<br>

Manajemen memintamu untuk memberikan data yang mereka butuhkan baik mengenai detail transaksi ataupun summary dari datanya. Sebagai Data Engineer, tujuanmu saat ini adalah untuk memprovide kebutuhan tersebut.

<img src="https://cdn.dribbble.com/userupload/21955253/file/original-cbc2133f09318197a07643d9033a3f16.gif" width="50%">

Untuk memenuhi kebutuhan tersebut, kamu akan melakukan proses ekstraksi dan pengolahan data dari **database** transaksi pizza menggunakan SQL. Data yang dihasilkan harus akurat, konsisten, dan mudah digunakan oleh tim bisnis maupun Data Analyst dalam proses analisis lebih lanjut. Hasil pengolahan data ini nantinya akan menjadi dasar pembuatan laporan dan dashboard yang digunakan manajemen untuk memantau performa penjualan, mengidentifikasi tren bisnis, serta mendukung pengambilan keputusan yang berbasis data. Selain itu, kamu juga perlu memastikan bahwa data yang disajikan memiliki struktur yang baik sehingga dapat diakses dan digunakan secara efisien oleh berbagai stakeholder di perusahaan.

# **Selayang Pandang**
Hampir semua aktivitas menghasilkan data. Mulai dari data pengguna aplikasi, data transaksi, hingga data hasil analisis, semuanya perlu dikelola dengan baik. Tanpa sistem yang tepat, data akan sulit dicari, tidak rapi, dan berpotensi menimbulkan kesalahan.

<img src="https://cdn.dribbble.com/userupload/42434609/file/original-b7e5f9185d73de1a362bf8644a56a67d.gif" width="40%"><br>
Database hadir sebagai solusi untuk mengelola data secara terstruktur dan efisien. Dengan database, data dapat disimpan dengan rapi, diakses dengan cepat, dan diperbarui sesuai kebutuhan. Hal ini sangat penting dalam pengembangan aplikasi, analisis data, maupun pengambilan keputusan berbasis data.

# **Database**

Database adalah kumpulan data yang tersimpan secara terstruktur sehingga dapat diakses, dikelola, dan diperbarui dengan mudah menggunakan komputer.

Jenis Database :
<ul>
<li><b>Relational Database</b></li>
Database yang menyimpan data dalam bentuk tabel (baris & kolom) dan saling berelasi.

<li><b>Non-Relational Database</b></li>
Database dengan struktur fleksibel, tidak berbasis tabel.<br><br>

<img src="https://www.scylladb.com/wp-content/uploads/differences-between-sql-databases-and-nosql-databases.png" width="50%">
</ul>

# **Tools Database - Google Big Query**

<img src="https://docs.cloud.google.com/static/bigquery/images/gc-bigquery-ready.png" width="40%">

Google BigQuery adalah tools database yang berfungsi sebagai data warehouse di cloud untuk menyimpan dan menganalisis data dalam jumlah sangat besar menggunakan SQL.

Dari sisi database, BigQuery memiliki karakteristik berikut:
* Menyimpan data dalam bentuk tabel seperti database pada umumnya (memiliki dataset, tabel, kolom, dan tipe data).
* Menggunakan SQL (GoogleSQL) untuk melakukan operasi database seperti SELECT, JOIN, GROUP BY, dan analisis data.
* Dioptimalkan untuk analisis data (OLAP), bukan untuk transaksi harian seperti database aplikasi.
* Dikelola sepenuhnya di cloud, sehingga pengguna tidak perlu mengatur server, storage, atau scaling.
* Mampu memproses data sangat besar (hingga terabyte atau petabyte) dengan query yang tetap cepat.

### 📝 **Task** : ***Membuat Project di Google Big Query***

**[Instruksi]** :       
* Buka <a href="console.cloud.google.com">console.cloud.google.com</a>
* Klik bagian Project > Klik New Project
* Lalu isikan `Project Name` dengan *fsbproject-123* (misalkan) lalu pastikan project id-nya <br><br> <img src="https://i.sstatic.net/O6WzG.png" width="35%">
* Klik button `CREATE`
* Lalu pilih project yang baru dibuat tersebut

# **Membuat Dataset**

Dataset di Google BigQuery adalah wadah (container) yang digunakan untuk mengelompokkan tabel, view, dan objek data lainnya dalam satu proyek.

- Penjelasan singkatnya **dataset adalah kumpulan tabel di dalam BigQuery**

<br>

Secara struktur kurang lebih sebagai berikut:
```
Project
   └── Dataset
         ├── Table
         ├── View
         └── External Table
```

### 📝 **Task** : ***Membuat Dataset di Google Big Query***

Setelah project dibuat, masuk ke bagian Google Big Query dan buat dataset dengan nama `pizza_transaction`

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/GBQ%20-%20Create%20Dataset.png" width="40%">

# **Tipe Data**

Tipe data adalah klasifikasi jenis nilai yang dapat disimpan dan diproses oleh suatu sistem (seperti bahasa pemrograman atau basis data).
Tipe data menentukan:
* Bentuk data (angka, teks, tanggal, dll)
* Ukuran penyimpanan
* Operasi yang bisa dilakukan
* Aturan validasi data

<br>

Pada SQL beberapa tipe data yang umum digunakan adalah sebagai berikut :
<br><br>

<table>
  <thead>
    <tr>
      <th>Kategori</th>
      <th>Tipe Data</th>
      <th>Deskripsi</th>
      <th>Contoh</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Numeric</td>
      <td>INT64</td>
      <td>Bilangan bulat 64-bit</td>
      <td>100</td>
    </tr>
    <tr>
      <td>Numeric</td>
      <td>FLOAT64</td>
      <td>Bilangan pecahan presisi ganda</td>
      <td>3.1415</td>
    </tr>
    <tr>
      <td>Numeric</td>
      <td>NUMERIC</td>
      <td>Bilangan desimal presisi tinggi (hingga 38 digit)</td>
      <td>12345.67</td>
    </tr>
    <tr>
      <td>Numeric</td>
      <td>BIGNUMERIC</td>
      <td>Bilangan desimal presisi sangat tinggi (hingga 76 digit)</td>
      <td>12345678901234567890.123456</td>
    </tr>
    <tr>
      <td>Character</td>
      <td>STRING</td>
      <td>Teks dengan panjang variabel (UTF-8)</td>
      <td>"Halo BigQuery"</td>
    </tr>
    <tr>
      <td>Binary</td>
      <td>BYTES</td>
      <td>Data biner dengan panjang variabel</td>
      <td>b"abc"</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>DATE</td>
      <td>Tanggal (YYYY-MM-DD)</td>
      <td>2026-01-01</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>TIME</td>
      <td>Waktu tanpa tanggal</td>
      <td>10:30:00</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>DATETIME</td>
      <td>Tanggal dan waktu tanpa zona waktu</td>
      <td>2026-01-01 10:30:00</td>
    </tr>
    <tr>
      <td>Date/Time</td>
      <td>TIMESTAMP</td>
      <td>Titik waktu absolut (UTC)</td>
      <td>2026-01-01 10:30:00 UTC</td>
    </tr>
    <tr>
      <td>Boolean</td>
      <td>BOOL</td>
      <td>Nilai benar atau salah</td>
      <td>TRUE</td>
    </tr>
    <tr>
      <td>JSON</td>
      <td>JSON</td>
      <td>Menyimpan data JSON secara native</td>
      <td>{"nama":"Ani"}</td>
    </tr>
    <tr>
      <td>Complex</td>
      <td>ARRAY</td>
      <td>Daftar elemen dengan tipe data yang sama</td>
      <td>[1,2,3]</td>
    </tr>
    <tr>
      <td>Complex</td>
      <td>STRUCT</td>
      <td>Kumpulan field seperti objek / record</td>
      <td>STRUCT("Ani" AS nama, 20 AS umur)</td>
    </tr>
    <tr>
      <td>Geospatial</td>
      <td>GEOGRAPHY</td>
      <td>Data geospasial seperti titik, garis, dan polygon</td>
      <td>ST_GEOGPOINT(106.8, -6.2)</td>
    </tr>
  </tbody>
</table>

<br>docs : *https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/data-types*

# **Membuat Table**

Tabel di dalam database dapat dibuat dengan mengeksekusi perintah berikut:

Membuat tabel dari file (CSV / JSON / Parquet)
* Klik “Create Table” → Source → Upload
* Pilih file (CSV, JSON, Parquet, Avro)
* Pilih Destination Dataset / Table
* Pilih Schema:
* Auto-detect → biar BigQuery deteksi tipe data otomatis
* Edit manually → jika ingin set tipe data spesifik
* Klik “Create Table”

### 📝 **Task** : ***Menambahkan Data pada Tabel***

Unggah seluruh data pada file `Pizza Transaction Dataset.zip` untuk dimasukan pada tabel, sesuaikan namanya dengan nama filenya dan lakukan hingga semua selesai

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/GBQ%20-%20Create%20Table.png" width="50%">

Jika semua sudah terupload maka akan muncul tampilan seperti berikut

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/GBQ%20-%20Dataset%20Uploaded.png" width="30%">

---

#**Set Up**

Untuk dapat menghubungkan Google Colab dengan layanan Google Cloud, khususnya agar bisa mengakses dan mengelola data di BigQuery perlu dilakukan proses autentikasi user terlebih dahulu. Jalankan proses dibawah ini sesuai instruksi

In [1]:
# Import library yang dibutuhkan
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [10]:
# Isikan dengan project id masing-masing
project_id = "fsbproject-123-498902"

# Lalu hubungkan ke Client Big Query
client = bigquery.Client(project = project_id)

Jika semua proses tercentang, maka saat ini colabmu sudah berhasil terhubung ke google BigQuery

# **Mengakses Data**

Perintah `SELECT` bertujuan untuk mengambil dan menampilkan data dari tabel di database. Ini penting untuk analisis karena saat menganalisa data perlu mengakses data yang relevan untuk dianalisis seperti mengidentifikasi pola, tren, dan informasi penting lainnya.

## **Menampilkan Semua Data pada Satu Tabel**

Untuk dapat menampilkan semua isi (data) pada sebuah tabel di Google BigQuery, eksekusi perintah

```
SELECT * FROM dataset_id.nama_tabel
```

Dalam perintah `SELECT`, tanda bintang (*) digunakan untuk memilih semua kolom dari tabel yang disebutkan. Cara ini merupakan cara cepat untuk mengambil seluruh data tanpa perlu menyebutkan nama-nama kolom satu per satu.

<br>docs : *https://www.postgresql.org/docs/current/sql-select.html*

### 📝 **Task** : ***Mengakses Data pada Table***

Untuk mempelajari / mengeksplor semua data yang ada pada database `pizza_transaction`, akan ditampilkan semua data pada tabel berikut :      
- trx_order
- trx_order_detail
- mst_pizza
- mst_pizza_type
- mst_customer

In [11]:
%%bigquery --project {project_id} --verbose

-- Tampilkan data `trx_order`
SELECT * FROM pizza_transaction.trx_order

Executing query with job ID: 30b4f946-ad8b-4487-9f9f-f5838ebff0bf
Query executing: 1.89s
Job ID 30b4f946-ad8b-4487-9f9f-f5838ebff0bf successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,created_date,updated_date
0,TRX000026,CUST006333,EMP000208,01/01/2025,14:54:26,15:23:02,0,None,2025-01-01 14:54:31,<NA>
1,TRX000037,CUST003319,EMP000208,01/01/2025,16:56:09,17:18:48,0,None,2025-01-01 16:56:14,<NA>
2,TRX000057,CUST008422,EMP000208,01/01/2025,19:10:51,19:30:38,0,None,2025-01-01 19:10:56,<NA>
3,TRX000077,CUST001979,EMP000208,01/02/2025,12:22:46,12:41:29,0,None,2025-01-02 12:22:51,<NA>
4,TRX000087,CUST004837,EMP000208,01/02/2025,14:01:02,14:29:46,0,None,2025-01-02 14:01:07,<NA>
...,...,...,...,...,...,...,...,...,...,...
21345,TRX009714,CUST004609,EMP000756,06/12/2025,15:32:54,15:52:27,1,Wrong pizza size,2025-06-12 15:32:59,<NA>
21346,TRX011127,CUST003549,EMP000756,07/05/2025,12:49:09,13:03:28,1,Wrong pizza size,2025-07-05 12:49:14,<NA>
21347,TRX011178,CUST008535,EMP000756,07/06/2025,13:09:22,13:28:47,1,Wrong pizza size,2025-07-06 13:09:27,<NA>
21348,TRX012098,CUST001979,EMP000756,07/21/2025,18:11:15,18:33:56,1,Wrong pizza size,2025-07-21 18:11:20,<NA>
21349,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,2025-11-30 17:07:40,<NA>

Setelah berhasil mendapatkan data pada table trx_order, buat data dictionary dengan bantuan Gemini AI (fitur bawaan pada Google Colab). Contoh prompt yang bisa dilakukan terlampir sebagai berikut :

*"Buatkan data dictionary (dalam bahasa indonesia) berbentuk table html pada tabel pizza_transaction.trx_order hanya nama kolom dan deskripsinya saja agar bisa langsung di copy di markdown colab"*

<br>
<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/GBQ%20-%20Gemini%20for%20Data%20Dictionary.png" width="60%">

Data dictionary untuk table `trx_order`

<table>
  <thead>
    <tr>
      <th>Nama Kolom</th>
      <th>Deskripsi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>order_id</code></td>
      <td>Pengidentifikasi unik untuk setiap pesanan.</td>
    </tr>
    <tr>
      <td><code>customer_id</code></td>
      <td>Pengidentifikasi untuk pelanggan yang membuat pesanan.</td>
    </tr>
    <tr>
      <td><code>order_maker_id</code></td>
      <td>Pengidentifikasi untuk karyawan yang memproses pesanan.</td>
    </tr>
    <tr>
      <td><code>order_date</code></td>
      <td>Tanggal pesanan dibuat.</td>
    </tr>
    <tr>
      <td><code>order_time</code></td>
      <td>Waktu pesanan dibuat.</td>
    </tr>
    <tr>
      <td><code>completion_time</code></td>
      <td>Waktu pesanan selesai.</td>
    </tr>
    <tr>
      <td><code>is_complain</code></td>
      <td>Menunjukkan apakah ada keluhan untuk pesanan (0 = Tidak, 1 = Ya).</td>
    </tr>
    <tr>
      <td><code>complain_detail</code></td>
      <td>Rincian keluhan, jika ada.</td>
    </tr>
    <tr>
      <td><code>created_date</code></td>
      <td>Timestamp saat record dibuat.</td>
    </tr>
    <tr>
      <td><code>updated_date</code></td>
      <td>Timestamp saat record terakhir diperbarui.</td>
    </tr>
  </tbody>
</table>

In [12]:
%%bigquery --project {project_id} --verbose

-- Tampilkan data `trx_order_detail`
SELECT * FROM pizza_transaction.trx_order_detail

Executing query with job ID: 6586fb1a-5613-425a-a413-42bb46363d04
Query executing: 1.64s
Job ID 6586fb1a-5613-425a-a413-42bb46363d04 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_details_id,order_id,pizza_id,quantity,created_date,updated_date
0,TRXD000001,TRX000001,PIZZA_HAWAIIAN_M,1,2025-01-01 11:38:41,<NA>
1,TRXD000002,TRX000002,PIZZA_CLASSIC_DLX_M,1,2025-01-01 11:57:45,<NA>
2,TRXD000003,TRX000002,PIZZA_FIVE_CHEESE_L,1,2025-01-01 11:57:45,<NA>
3,TRXD000004,TRX000002,PIZZA_ITAL_SUPR_L,1,2025-01-01 11:57:45,<NA>
4,TRXD000005,TRX000002,PIZZA_MEXICANA_M,1,2025-01-01 11:57:45,<NA>
...,...,...,...,...,...,...
48618,TRXD048617,TRX021348,PIZZA_FOUR_CHEESE_L,1,2025-12-31 21:23:15,<NA>
48619,TRXD048617,TRX021348,PIZZA_FOUR_CHEESE_L,1,2025-12-31 21:23:15,<NA>
48620,TRXD048618,TRX021348,PIZZA_NAPOLITANA_S,1,2025-12-31 21:23:15,<NA>
48621,TRXD048619,TRX021349,PIZZA_MEXICANA_L,1,2025-12-31 22:09:59,<NA>
48622,TRXD048620,TRX021350,PIZZA_BBQ_CKN_S,1,2025-12-31 23:02:10,<NA>

Data dictionary untuk table `trx_order_detail`

...

<table>
  <thead>
    <tr>
      <th>Nama Kolom</th>
      <th>Deskripsi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>order_details_id</code></td>
      <td>Pengidentifikasi unik untuk setiap detail pesanan.</td>
    </tr>
    <tr>
      <td><code>order_id</code></td>
      <td>Pengidentifikasi pesanan yang terkait.</td>
    </tr>
    <tr>
      <td><code>pizza_id</code></td>
      <td>Pengidentifikasi pizza yang dipesan.</td>
    </tr>
    <tr>
      <td><code>quantity</code></td>
      <td>Jumlah pizza yang dipesan.</td>
    </tr>
    <tr>
      <td><code>created_date</code></td>
      <td>Timestamp saat record dibuat.</td>
    </tr>
    <tr>
      <td><code>updated_date</code></td>
      <td>Timestamp saat record terakhir diperbarui.</td>
    </tr>
  </tbody>
</table>

In [13]:
%%bigquery --project {project_id} --verbose

-- Tampilkan data `mst_pizza`
SELECT * FROM pizza_transaction.mst_pizza

Executing query with job ID: 252ff3c1-d253-4754-b9d3-1c5d1b57167b
Query executing: 0.80s
Job ID 252ff3c1-d253-4754-b9d3-1c5d1b57167b successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,pizza_id,pizza_type_id,size,price,production_cost,created_date,updated_date
0,PIZZA_PEPPERONI_L,PIZZA_TYPE_PEPPERONI,L,IDR123525,IDR96390,2024-12-31 00:00:00,<NA>
1,PIZZA_HAWAIIAN_L,PIZZA_TYPE_HAWAIIAN,L,IDR133650,IDR102951,2024-12-31 00:00:00,<NA>
2,PIZZA_PEP_MSH_PEP_L,PIZZA_TYPE_PEP_MSH_PEP,L,IDR141750,IDR111537,2024-12-31 00:00:00,<NA>
3,PIZZA_FOUR_CHEESE_L,PIZZA_TYPE_FOUR_CHEESE,L,IDR145395,IDR113724,2024-12-31 00:00:00,<NA>
4,PIZZA_FIVE_CHEESE_L,PIZZA_TYPE_FIVE_CHEESE,L,IDR149850,IDR124740,2024-12-31 00:00:00,<NA>
...,...,...,...,...,...,...,...
91,PIZZA_VEGGIE_VEG_S,PIZZA_TYPE_VEGGIE_VEG,S,IDR97200,IDR69093,2024-12-31 00:00:00,<NA>
92,PIZZA_CALABRESE_S,PIZZA_TYPE_CALABRESE,S,IDR99225,IDR81891,2024-12-31 00:00:00,<NA>
93,PIZZA_SICILIAN_S,PIZZA_TYPE_SICILIAN,S,IDR99225,IDR71685,2024-12-31 00:00:00,<NA>
94,PIZZA_THE_GREEK_XL,PIZZA_TYPE_THE_GREEK,XL,IDR206550,IDR157221,2024-12-31 00:00:00,<NA>
95,PIZZA_THE_GREEK_XXL,PIZZA_TYPE_THE_GREEK,XXL,IDR291195,IDR260738,2024-12-31 00:00:00,<NA>

Data dictionary untuk table `mst_pizza`

<table>
  <thead>
    <tr>
      <th>Nama Kolom</th>
      <th>Deskripsi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>pizza_id</code></td>
      <td>Pengidentifikasi unik untuk setiap pizza.</td>
    </tr>
    <tr>
      <td><code>pizza_type_id</code></td>
      <td>Pengidentifikasi tipe pizza.</td>
    </tr>
    <tr>
      <td><code>size</code></td>
      <td>Ukuran pizza (misalnya, S, M, L, XL, XXL).</td>
    </tr>
    <tr>
      <td><code>price</code></td>
      <td>Harga jual pizza.</td>
    </tr>
    <tr>
      <td><code>production_cost</code></td>
      <td>Biaya produksi pizza.</td>
    </tr>
    <tr>
      <td><code>created_date</code></td>
      <td>Timestamp saat record dibuat.</td>
    </tr>
    <tr>
      <td><code>updated_date</code></td>
      <td>Timestamp saat record terakhir diperbarui.</td>
    </tr>
  </tbody>
</table>

In [14]:
%%bigquery --project {project_id} --verbose

-- Tampilkan data `mst_pizza_type`
SELECT * FROM pizza_transaction.mst_pizza_type

Executing query with job ID: c03beb8b-f28e-4da3-b16a-c10f63e16c47
Query executing: 0.64s
Job ID c03beb8b-f28e-4da3-b16a-c10f63e16c47 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,pizza_type_id,name,category,ingredients,created_date,updated_date
0,PIZZA_TYPE_BBQ_CKN,THE BARBECUE CHICKEN PIZZA,CHICKEN,"Barbecued Chicken, Red Peppers, Green Peppers,...",2024-12-31 00:00:00,<NA>
1,PIZZA_TYPE_CALI_CKN,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ...",2024-12-31 00:00:00,<NA>
2,PIZZA_TYPE_SOUTHW_CKN,THE SOUTHWEST CHICKEN PIZZA,CHICKEN,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja...",2024-12-31 00:00:00,<NA>
3,PIZZA_TYPE_CLASSIC_DLX,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2024-12-31 00:00:00,<NA>
4,PIZZA_TYPE_HAWAIIAN,THE HAWAIIAN PIZZA,CLASSIC,"Sliced Ham, Pineapple, Mozzarella Cheese",2024-12-31 00:00:00,<NA>
5,PIZZA_TYPE_PEPPERONI,THE PEPPERONI PIZZA,CLASSIC,"Mozzarella Cheese, Pepperoni",2024-12-31 00:00:00,<NA>
6,PIZZA_TYPE_THE_GREEK,THE GREEK PIZZA,CLASSIC,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",2024-12-31 00:00:00,<NA>
7,PIZZA_TYPE_BIG_MEAT,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",2024-12-31 00:00:00,<NA>
8,PIZZA_TYPE_NAPOLITANA,THE NAPOLITANA PIZZA,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",2024-12-31 00:00:00,<NA>
9,PIZZA_TYPE_CALABRESE,THE CALABRESE PIZZA,SUPREME,"‘Nduja Salami, Pancetta, Tomatoes, Red Onions,...",2024-12-31 00:00:00,<NA>
10,PIZZA_TYPE_PEPPR_SALAMI,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ...",2024-12-31 00:00:00,<NA>
11,PIZZA_TYPE_SICILIAN,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives...",2024-12-31 00:00:00,<NA>
12,PIZZA_TYPE_SPICY_ITAL,THE SPICY ITALIAN PIZZA,SUPREME,"Capocollo, Tomatoes, Goat Cheese, Artichokes, ...",2024-12-31 00:00:00,<NA>
13,PIZZA_TYPE_SOPPRESSATA,THE SOPPRESSATA PIZZA,Supreme,"Soppressata Salami, Fontina Cheese, Mozzarella...",2024-12-31 00:00:00,<NA>
14,PIZZA_TYPE_ITAL_VEGGIE,THE ITALIAN VEGETABLES PIZZA,VEGGIE,"Eggplant, Artichokes, Tomatoes, Zucchini, Red ...",2024-12-31 00:00:00,<NA>
15,PIZZA_TYPE_MEDITERRANEO,THE MEDITERRANEAN PIZZA,VEGGIE,"Spinach, Artichokes, Kalamata Olives, Sun-drie...",2024-12-31 00:00:00,<NA>
16,PIZZA_TYPE_SPIN_PESTO,THE SPINACH PESTO PIZZA,VEGGIE,"Spinach, Artichokes, Tomatoes, Sun-dried Tomat...",2024-12-31 00:00:00,<NA>
17,PIZZA_TYPE_SPINACH_FET,THE SPINACH AND FETA PIZZA,VEGGIE,"Spinach, Mushrooms, Red Onions, Feta Cheese, G...",2024-12-31 00:00:00,<NA>
18,PIZZA_TYPE_CKN_ALFREDO,THE CHICKEN ALFREDO PIZZA,chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",2024-12-31 00:00:00,<NA>
19,PIZZA_TYPE_CKN_PESTO,THE CHICKEN PESTO PIZZA,chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli...",2024-12-31 00:00:00,<NA>
20,PIZZA_TYPE_THAI_CKN,THE THAI CHICKEN PIZZA,chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha...",2024-12-31 00:00:00,<NA>
21,PIZZA_TYPE_ITAL_CPCLLO,THE ITALIAN CAPOCOLLO PIZZA,classic,"Capocollo, Red Peppers, Tomatoes, Goat Cheese,...",2024-12-31 00:00:00,<NA>
22,PIZZA_TYPE_PEP_MSH_PEP,"THE PEPPERONI, MUSHROOM AND PEPPERS PIZZA",classic,"Pepperoni, Mushrooms, Green Peppers",2024-12-31 00:00:00,<NA>
23,PIZZA_TYPE_BRIE_CARRE,THE BRIE CARRE PIZZA,supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni...",2024-12-31 00:00:00,<NA>
24,PIZZA_TYPE_ITAL_SUPR,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2024-12-31 00:00:00,<NA>
25,PIZZA_TYPE_PRSC_ARGLA,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella...",2024-12-31 00:00:00,<NA>
26,PIZZA_TYPE_SPINACH_SUPR,THE SPINACH SUPREME PIZZA,supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",2024-12-31 00:00:00,<NA>
27,PIZZA_TYPE_FIVE_CHEESE,THE FIVE CHEESE PIZZA,veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2024-12-31 00:00:00,<NA>
28,PIZZA_TYPE_FOUR_CHEESE,THE FOUR CHEESE PIZZA,veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",2024-12-31 00:00:00,<NA>
29,PIZZA_TYPE_GREEN_GARDEN,THE GREEN GARDEN PIZZA,veggie,"Spinach, Mushrooms, Tomatoes, Green Olives, Fe...",2024-12-31 00:00:00,<NA>
30,PIZZA_TYPE_MEXICANA,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2024-12-31 00:00:00,<NA>
31,PIZZA_TYPE_VEGGIE_VEG,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",2024-12-31 00:00:00,<NA>

Data dictionary untuk table `mst_pizza_type`

<table>
  <thead>
    <tr>
      <th>Nama Kolom</th>
      <th>Deskripsi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>pizza_type_id</code></td>
      <td>Pengidentifikasi unik untuk setiap tipe pizza.</td>
    </tr>
    <tr>
      <td><code>name</code></td>
      <td>Nama lengkap tipe pizza.</td>
    </tr>
    <tr>
      <td><code>category</code></td>
      <td>Kategori pizza (misalnya, Classic, Chicken, Veggie).</td>
    </tr>
    <tr>
      <td><code>ingredients</code></td>
      <td>Daftar bahan-bahan yang digunakan dalam pizza.</td>
    </tr>
    <tr>
      <td><code>created_date</code></td>
      <td>Timestamp saat record dibuat.</td>
    </tr>
    <tr>
      <td><code>updated_date</code></td>
      <td>Timestamp saat record terakhir diperbarui.</td>
    </tr>
  </tbody>
</table>

In [15]:
%%bigquery --project {project_id} --verbose

-- Tampilkan data `mst_customer`
SELECT * FROM pizza_transaction.mst_customer

Executing query with job ID: 69bfc427-ba9e-486f-8a54-0c3725eb3233
Query executing: 0.73s
Job ID 69bfc427-ba9e-486f-8a54-0c3725eb3233 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,customer_id,customer_name,gender,birth_date,phone_number,email,open_date,created_date,updated_date
0,CUST007150,Salsabila Purnawati,F,1990-09-17,081 074 0279,salsabila.purnawati@hotmail.com,2024/12/31,2024-12-31 18:55:01,<NA>
1,CUST003319,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,2024-12-31 17:24:59,<NA>
2,CUST007254,Elma Maryati,F,1984-03-25,+62-008-153-1104,elma.maryati@yahoo.com,2024/12/31,2024-12-31 00:48:10,<NA>
3,CUST004392,Najwa Natsir,F,1980-05-25,+62 (678) 311-9386,najwa.natsir@hotmail.com,2024/12/31,2024-12-31 17:41:05,<NA>
4,CUST005127,Hani Palastri,F,2003-02-10,+62 (368) 876-1503,hani.palastri@hotmail.com,2024/12/31,2024-12-31 18:37:35,<NA>
...,...,...,...,...,...,...,...,...,...
132,CUST009056,Gada Winarsih,M,2000-12-07,0809259635,gada.winarsih@hotmail.com,2025/09/11,2025-09-11 11:12:13,<NA>
133,CUST009366,Mulyanto Suryono,M,2001-02-17,+62-0885-877-0893,mulyanto.suryono@yahoo.com,2025/09/11,2025-09-11 11:12:13,<NA>
134,CUST009522,Cakrawangsa Hutagalung,M,1989-03-25,+62 (39) 581-0404,cakrawangsa.hutagalung@gmail.com,2025/09/11,2025-09-11 11:12:13,<NA>
135,CUST009700,Asirwanda Hidayat,M,1991-01-15,0837121476,asirwanda.hidayat@hotmail.com,2025/09/11,2025-09-11 11:12:13,<NA>
136,CUST009875,Wadi Jailani,M,1996-02-28,088 915 7132,wadi.jailani@yahoo.com,2025/09/11,2025-09-11 11:12:13,<NA>

Data dictionary untuk table `mst_customer`

<table>
  <thead>
    <tr>
      <th>Nama Kolom</th>
      <th>Deskripsi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>customer_id</code></td>
      <td>Pengidentifikasi unik untuk setiap pelanggan.</td>
    </tr>
    <tr>
      <td><code>customer_name</code></td>
      <td>Nama lengkap pelanggan.</td>
    </tr>
    <tr>
      <td><code>gender</code></td>
      <td>Jenis kelamin pelanggan (misalnya, Pria, Wanita).</td>
    </tr>
    <tr>
      <td><code>birth_date</code></td>
      <td>Tanggal lahir pelanggan.</td>
    </tr>
    <tr>
      <td><code>phone_number</code></td>
      <td>Nomor telepon pelanggan.</td>
    </tr>
    <tr>
      <td><code>email</code></td>
      <td>Alamat email pelanggan.</td>
    </tr>
    <tr>
      <td><code>open_date</code></td>
      <td>Tanggal pembukaan akun pelanggan.</td>
    </tr>
    <tr>
      <td><code>created_date</code></td>
      <td>Timestamp saat record dibuat.</td>
    </tr>
    <tr>
      <td><code>updated_date</code></td>
      <td>Timestamp saat record terakhir diperbarui.</td>
    </tr>
  </tbody>
</table>

## **Menampilkan Kolom Tertentu pada Satu Tabel**

Untuk dapat menampilkan isi data pada kolom tertentu pada sebuah tabel, eksekusi perintah

```
SELECT nama_kolom1, nama_kolom2, ... FROM nama_tabel
```

Gunakan tanda koma untuk mendaftarkan nama kolom yang ingin ditampilkan. Kolom yang disebutkan pertama kali akan ditampilkan paling kiri begitu juga dengan kolom kedua hingga kolom terakhir.

### 📝 **Task** : ***Tampilkan Kolom Tertentu pada Data***

Analisa akan difokuskan ke transaksi customer tiap tanggalnya. Tampilkan hanya kolom `order_id`, `customer_id` dan `order_date` dan `complain_detail` pada data!

In [18]:
%%bigquery --project {project_id} --verbose

-- Tampilkan data
SELECT order_id, customer_id, order_date, complain_detail
FROM pizza_transaction.trx_order

Executing query with job ID: f8b9dbef-7751-473b-a157-3e813a7bcef6
Query executing: 0.61s
Job ID f8b9dbef-7751-473b-a157-3e813a7bcef6 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

        order_id customer_id  order_date   complain_detail
0      TRX000026  CUST006333  01/01/2025              None
1      TRX000037  CUST003319  01/01/2025              None
2      TRX000057  CUST008422  01/01/2025              None
3      TRX000077  CUST001979  01/02/2025              None
4      TRX000087  CUST004837  01/02/2025              None
...          ...         ...         ...               ...
21345  TRX009714  CUST004609  06/12/2025  Wrong pizza size
21346  TRX011127  CUST003549  07/05/2025  Wrong pizza size
21347  TRX011178  CUST008535  07/06/2025  Wrong pizza size
21348  TRX012098  CUST001979  07/21/2025  Wrong pizza size
21349  TRX019645  CUST001120  11/30/2025  Wrong pizza size

[21350 rows x 4 columns]

## **Menyaring Nilai Berdasarkan Kondisi Tertentu**

Untuk melakukan penyaringan nilai berdasarkan kondisi tertentu dapat menggunakan <b>Comparison Operators</b>. Operator perbandingan (<i>comparison operators</i>) dalam SQL digunakan untuk membandingkan nilai-nilai dan menentukan bagaimana data memenuhi kondisi tertentu. Operator pembanding pada SQL disimbolkan dengan beberapa tanda berikut
<br><br>
<table border="1">
    <tr>
        <th>Tanda</th>
        <th>Deskripsi</th>
        <th>Contoh</th>
    </tr>
    <tr>
        <td>=</td>
        <td>Sama dengan (<i>Equals</i>)</td>
        <td>A = B</td>
    </tr>
    <tr>
        <td><></td>
        <td>Tidak Sama dengan (<i>Not Equals</i>)</td>
        <td>A <> B</td>
    </tr>
    <tr>
        <td><</td>
        <td>Kurang dari (<i>Less than</i>)</td>
        <td>A < B</td>
    </tr>
    <tr>
        <td>></td>
        <td>Lebih dari (<i>More than</i>)</td>
        <td>A > B</td>
    </tr>
    <tr>
        <td><=</td>
        <td>Kurang dari sama dengan (<i>Less than or Equals To</i>)</td>
        <td>A <= B</td>
    </tr>
    <tr>
        <td>>=</td>
        <td>Lebih dari sama dengan (<i>More than or Equals To</i>)</td>
        <td>A >= B</td>
    </tr>
</table>

<br>Kemudian gunakan operator pembanding tersebut kedalam sebuah kondisi <br><br>
```
SELECT * FROM nama_table
WHERE kondisi;
```

### 📝 **Task** : ***Pengkondisian***

Manajer ingin memfokuskan untuk melihat transaksi yang sempat mengalami komplain oleh pelanggan. Tampilkan data tersebut!

In [19]:
%%bigquery --project {project_id} --verbose

SELECT * FROM pizza_transaction.trx_order
WHERE is_complain = 1

Executing query with job ID: 1e7e2bd8-270e-4046-ae65-6e6008090edf
Query executing: 0.93s
Job ID 1e7e2bd8-270e-4046-ae65-6e6008090edf successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,created_date,updated_date
0,TRX000815,CUST004105,EMP000208,01/14/2025,16:38:00,16:56:42,1,Dough undercooked,2025-01-14 16:38:05,<NA>
1,TRX004162,CUST005429,EMP000208,03/11/2025,18:27:59,18:39:08,1,Dough undercooked,2025-03-11 18:28:04,<NA>
2,TRX004181,CUST003228,EMP000208,03/12/2025,12:08:19,12:29:46,1,Dough undercooked,2025-03-12 12:08:24,<NA>
3,TRX007992,CUST005210,EMP000208,05/14/2025,18:20:55,18:36:19,1,Dough undercooked,2025-05-14 18:21:00,<NA>
4,TRX008846,CUST006333,EMP000208,05/29/2025,11:18:27,11:36:31,1,Dough undercooked,2025-05-29 11:18:32,<NA>
...,...,...,...,...,...,...,...,...,...,...
2130,TRX009714,CUST004609,EMP000756,06/12/2025,15:32:54,15:52:27,1,Wrong pizza size,2025-06-12 15:32:59,<NA>
2131,TRX011127,CUST003549,EMP000756,07/05/2025,12:49:09,13:03:28,1,Wrong pizza size,2025-07-05 12:49:14,<NA>
2132,TRX011178,CUST008535,EMP000756,07/06/2025,13:09:22,13:28:47,1,Wrong pizza size,2025-07-06 13:09:27,<NA>
2133,TRX012098,CUST001979,EMP000756,07/21/2025,18:11:15,18:33:56,1,Wrong pizza size,2025-07-21 18:11:20,<NA>
2134,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,2025-11-30 17:07:40,<NA>

## **Menyaring Nilai Berdasarkan Beberapa Kondisi**

Untuk melakukan penyaringan nilai berdasarkan beberapa kondisi dapat menggunakan <b>Logical Operators</b>. Operator logika (<i>logical operator</i>) adalah simbol atau kata kunci yang digunakan untuk menghubungkan dua atau lebih ekspresi logis dan menghasilkan nilai logis baru berdasarkan operasi tersebut. Operator logika pada SQL disimbolkan dengan beberapa tanda berikut
<br><br>
<table border="1">
    <tr>
        <th>Tanda</th>
        <th>Deskripsi</th>
        <th>Kondisi</th>
        <th>Contoh</th>
    </tr>
    <tr>
        <td><b>AND</b></td>
        <td>Operator penghubung 'DAN'</td>
        <td><i>Statement</i> bernilai benar jika keduanya benar / terpenuhi,<br>jika tidak demikian maka bernilai salah</td>
        <td>Condition 1 <b>AND</b> Condition 2</td>
    </tr>
    <tr>
        <td><b>OR</b></td>
        <td>Operator penghubung 'ATAU'</td>
        <td><i>Statement</i> bernilai salah jika keduanya salah / tidak terpenuhi,<br>jika tidak demikian maka bernilai benar</td>
        <td>Condition 1 <b>OR</b> Condition 2</td>
    </tr>
    <tr>
        <td><b>NOT</b></td>
        <td>Operator 'BUKAN'</td>
        <td>Operator ini membalikkan nilai logis dari ekspresi yang dioperasikan</td>
        <td><b>NOT</b> Condition 1</td>
    </tr>
</table>
<br><br>
Saat digunakan, untuk menyaring dua atau lebih pernyataan dengan operator logika akan berlaku kriteria sebagai berikut
<br><br>
<table border="1">
    <tr>
        <th>Condition 1</th>
        <th>Condition 2</th>
        <th>Condition 1 <span style='color:#55679C'>AND</span> Condition 2</th>
        <th>Condition 1 <span style='color:#55679C'>OR</span> Condition 2</th>
    </tr>
    <tr>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
    </tr>
</table>

Saat query dijalankan, hanya output yang bernilai benar saja yang akan ditampilkan.

<br>Kemudian gunakan operator pembanding tersebut kedalam sebuah kondisi <br><br>
```
SELECT nama_kolom FROM nama_tabel
WHERE kondisi1 AND/OR kondisi2
```

### 📝 **Task** : ***Multi Kondisi***

Diketahui bahwa pada tanggal 27 November 2025, restaurant pizza menerima paling banyak komplain di tanggal tersebut. Tampilkan data transaksi di tanggal tersebut yang sempat mengalami komplain!

In [22]:
%%bigquery --project {project_id} --verbose

SELECT * FROM pizza_transaction.trx_order
WHERE order_date = '11/27/2025' AND is_complain = 1

Executing query with job ID: e8f3cce1-8355-4a6f-98c1-6d949c119a89
Query executing: 0.59s
Job ID e8f3cce1-8355-4a6f-98c1-6d949c119a89 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,created_date,updated_date
0,TRX019460,CUST008782,EMP000302,11/27/2025,18:13:40,18:38:58,1,Dough undercooked,2025-11-27 18:13:45,<NA>
1,TRX019496,CUST004547,EMP000646,11/27/2025,20:52:37,21:03:29,1,Dough undercooked,2025-11-27 20:52:42,<NA>
2,TRX019442,CUST001988,EMP000286,11/27/2025,16:05:00,16:25:23,1,Missing toppings,2025-11-27 16:05:05,<NA>
3,TRX019476,CUST005429,EMP000560,11/27/2025,19:13:38,19:34:10,1,Missing toppings,2025-11-27 19:13:43,<NA>
4,TRX019458,CUST005429,EMP000665,11/27/2025,17:58:06,18:23:04,1,Missing toppings,2025-11-27 17:58:11,<NA>
5,TRX019441,CUST004293,EMP000302,11/27/2025,16:00:42,16:17:57,1,Order took too long,2025-11-27 16:00:47,<NA>
6,TRX019497,CUST009381,EMP000560,11/27/2025,20:54:24,21:09:01,1,Order took too long,2025-11-27 20:54:29,<NA>
7,TRX019465,CUST004293,EMP000208,11/27/2025,18:41:24,19:02:00,1,Pizza was burnt,2025-11-27 18:41:29,<NA>
8,TRX019438,CUST004537,EMP000646,11/27/2025,15:46:06,16:13:26,1,Pizza was burnt,2025-11-27 15:46:11,<NA>
9,TRX019433,CUST004392,EMP000756,11/27/2025,14:52:48,15:13:41,1,Pizza was burnt,2025-11-27 14:52:53,<NA>
10,TRX019464,CUST004354,EMP000756,11/27/2025,18:40:51,19:03:30,1,Pizza was burnt,2025-11-27 18:40:56,<NA>
11,TRX019406,CUST003549,EMP000231,11/27/2025,11:46:40,12:07:03,1,Received wrong pizza,2025-11-27 11:46:45,<NA>
12,TRX019488,CUST008535,EMP000646,11/27/2025,20:26:55,20:55:35,1,Received wrong pizza,2025-11-27 20:27:00,<NA>
13,TRX019429,CUST006843,EMP000295,11/27/2025,14:04:02,14:20:55,1,Wrong pizza size,2025-11-27 14:04:07,<NA>
14,TRX019443,CUST005205,EMP000665,11/27/2025,16:05:07,16:29:58,1,Wrong pizza size,2025-11-27 16:05:12,<NA>

# **Prefix**

Prefix merupakan penggunaan awalan pada nama tabel untuk memberikan informasi tambahan atau untuk mengelompokkan objek-objek tertentu. Sebagai contoh perhatikan gambar berikut :

```
SELECT t.nama_kolom1, t.nama_kolom2
FROM nama_tabel AS t
```

Nama tabel dimisalkan (diberi alias) sebagai tbl, lalu untuk mengakses kolom pada tabel tersebut bisa diberi prefix tbl.kolom1 dan seterusnya

### 📝 **Task** : ***Memberi Prefix***

Pada tabel pelanggan, ambil kolom customer_id, nama dan juga jenis kelaminnya namun gunakan alias 'c' pada nama tabel dan sematkan prefixnya saat mengakses kolom!

In [23]:
%%bigquery --project {project_id} --verbose

SELECT c.customer_id, c.customer_name, c.gender
FROM pizza_transaction.mst_customer AS c

Executing query with job ID: 08a94289-c7af-4339-ae9b-2cc5bf17b2b3
Query executing: 0.64s
Job ID 08a94289-c7af-4339-ae9b-2cc5bf17b2b3 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

    customer_id           customer_name gender
0    CUST007150     Salsabila Purnawati      F
1    CUST003319      Cornelia Wijayanti      F
2    CUST007254            Elma Maryati      F
3    CUST004392            Najwa Natsir      F
4    CUST005127           Hani Palastri      F
..          ...                     ...    ...
132  CUST009056           Gada Winarsih      M
133  CUST009366        Mulyanto Suryono      M
134  CUST009522  Cakrawangsa Hutagalung      M
135  CUST009700       Asirwanda Hidayat      M
136  CUST009875            Wadi Jailani      M

[137 rows x 3 columns]

# **Menggabungkan Tabel**

Data biasanya disimpan di berbagai tabel atau sistem yang berbeda pada RDBMS (Relational Database Management System). JOIN memungkinkan pengguna untuk menggabungkan data dari berbagai sumber untuk mendapatkan gambaran yang lebih lengkap. Memahami query JOIN memungkinkan seorang pengguna untuk mengintegrasikan dan menganalisis data secara efektif, sehingga dapat meningkatkan kualitas analisis dan mendukung pengambilan keputusan berbasis data.

Operasi JOIN standar dapat dilakukan jika terdapat kunci pada tiap tabel yang saling terhubung. Operasi join dasar yang paling umum digunakan ada 4 yakni :
<ul>
    <img src="https://media.licdn.com/dms/image/v2/D5622AQENtpe3uskDew/feedshare-shrink_800/feedshare-shrink_800/0/1702313123963?e=2147483647&v=beta&t=8moZqvVqoGRwHsTHZfRDCK-rcjCqb3DHqL3v2Bywh1Y" width="40%">
    <li><b>LEFT JOIN</b></li>
    LEFT JOIN adalah jenis operasi penggabungan baris dari dua tabel, tetapi hanya mengembalikan semua baris dari tabel kiri (tabel pertama) dan baris yang cocok dari tabel kanan (tabel kedua). Jika tidak ada kecocokan di tabel kanan, maka nilai-nilai untuk kolom dari tabel kanan akan diisi dengan NULL.
    <br>
    <li><b>RIGHT JOIN</b></li>
    RIGHT JOIN adalah jenis operasi penggabungan baris dari dua tabel, tetapi hanya mengembalikan semua baris dari tabel kanan (tabel kedua) dan baris yang cocok dari tabel kiri (tabel pertama). Jika tidak ada kecocokan di tabel kiri, maka nilai-nilai untuk kolom dari tabel kiri akan diisi dengan NULL.
    <br>
    <li><b>INNER JOIN</b></li>
    INNER JOIN adalah jenis operasi penggabungan yang hanya mengembalikan baris yang memiliki kecocokan di kedua tabel berdasarkan kriteria tertentu.
    <br>
    <li><b>FULL JOIN</b></li>
    FULL JOIN adalah jenis operasi penggabungan semua baris dari kedua tabel, baik yang memiliki kecocokan maupun yang tidak. Dengan demikian, hasilnya akan mencakup semua data dari tabel kiri dan tabel kanan.
    <br>
</ul>

### 📝 **Task** : ***Membuat ERD***

Untuk membantu memahami struktur dan hubungan data sebelum melakukan analisis SQL, biasa digunakan ERD (Entity Relationship Diagram). ERD adalah diagram yang digunakan untuk menggambarkan struktur hubungan antar data dalam sebuah database. Langkah-langkah pembuatan ERD adalah sebagai berikut :

* Untuk membuat ERD pada data Pizza Transaction dengan bantuan AI, buka situs https://www.eraser.io/ai/erd-generator

* Ketikan prompt: *"Sebuah table bernama trx_order_detail memiliki kolom 'order_details_id', 'order_id', 'pizza_id', 'quantity', 'created_date', 'updated_date'. Table dengan nama trx_order memiliki kolom 'order_id', 'customer_id', 'order_maker_id', 'order_date', 'order_time',  'completion_time', 'is_complain', 'complain_detail', 'created_date', 'updated_date'. Kemudian mst_pizza_type memiliki kolom 'pizza_type_id', 'name', 'category', 'ingredients', 'created_date', 'updated_date' lalu tabel mst_pizza memiliki kolom 'pizza_id', 'pizza_type_id', 'size', 'price', 'production_cost', 'created_date', 'updated_date' dan table mst_customer memiliki kolom 'customer_id', 'customer_name', 'gender', 'birth_date', 'phone_number', 'email', 'open_date', 'created_date', 'updated_date'. Buatkan ERD nya!"*

Jika berhasil maka akan tampil seperti gambar berikut

<img src="https://raw.githubusercontent.com/bachtiyarwork/Image/main/ERD%20-%20Pizza.jpg" width="60%">

Dengan terbentuknya ERD data Pizza Transaction maka struktur data menjadi lebih jelas dan terorganisir, sehingga hubungan antar tabel dapat dipahami dengan mudah. Hal ini memudahkan proses analisis data menggunakan SQL, terutama dalam melakukan join antar tabel untuk menghasilkan informasi transaksi yang utuh.

### 📝 **Task** : ***Menggabungkan Tabel***

Coba gabungkan dua tabel yakni tabel `trx_order` dan `trx_order_detail`, lalu tampilkan order_id, order_date, customer_id, quantity, pizza_id dan is_complain!

In [26]:
%%bigquery --project {project_id} --verbose

SELECT o.order_id, o.order_date, o.customer_id, od.quantity, od.pizza_id, o.is_complain
FROM pizza_transaction.trx_order AS o
JOIN pizza_transaction.trx_order_detail AS od
ON o.order_id = od.order_id

Executing query with job ID: d632d7b5-df1f-4173-b2b6-a9a41fa6c3e4
Query executing: 1.51s
Job ID d632d7b5-df1f-4173-b2b6-a9a41fa6c3e4 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,order_date,customer_id,quantity,pizza_id,is_complain
0,TRX000026,01/01/2025,CUST006333,1,PIZZA_CLASSIC_DLX_S,0
1,TRX000026,01/01/2025,CUST006333,1,PIZZA_VEGGIE_VEG_L,0
2,TRX000037,01/01/2025,CUST003319,1,PIZZA_ITAL_SUPR_L,0
3,TRX000037,01/01/2025,CUST003319,1,PIZZA_MEXICANA_L,0
4,TRX000057,01/01/2025,CUST008422,1,PIZZA_CLASSIC_DLX_M,0
...,...,...,...,...,...,...
48618,TRX012098,07/21/2025,CUST001979,1,PIZZA_PRSC_ARGLA_S,1
48619,TRX019645,11/30/2025,CUST001120,1,PIZZA_BIG_MEAT_S,1
48620,TRX019645,11/30/2025,CUST001120,1,PIZZA_MEXICANA_L,1
48621,TRX019645,11/30/2025,CUST001120,1,PIZZA_PEPPR_SALAMI_M,1
48622,TRX019645,11/30/2025,CUST001120,1,PIZZA_SICILIAN_L,1

# **Let's Soar Higher!**

Setelah melakukan banyak eksplorasi data dan cara mengakses datanya dengan menuliskan query, selanjutnya adalah coba *provide* kebutuhan query berikut!

### 📝 **Task** : ***Laporan Ringkasan Penjualan Harian***

Manajemen membutuhkan laporan ringkasan harian untuk menganalisis performa penjualan pizza. Buatlah sebuah laporan yang menampilkan metrik-metrik berikut ini per tanggal:

1.  **Tanggal Pesanan**
2.  **Total Transaksi**: Jumlah pesanan yang terjadi pada tanggal tersebut.
3.  **Total Pizza Terjual**: Total kuantitas pizza yang terjual.
4.  **Total Pendapatan (Revenue)**: Total nilai penjualan pizza.
5.  **Total Keuntungan (Profit)**: Total keuntungan yang didapatkan dari penjualan pizza (dengan mempertimbangkan harga jual dan biaya produksi).
6.  **Total Komplain**: Jumlah komplain yang tercatat pada tanggal tersebut.

Pastikan untuk menggabungkan data dari berbagai tabel yang ada, untuk mendapatkan semua informasi yang dibutuhkan. Perhatikan juga konversi tipe data yang mungkin diperlukan untuk perhitungan.

Note : *Untuk mendapatkan data sesuai kriteria pelajari konsep `Konversi Tipe Data`, `Fungsi JOIN`, `Agregasi` dan juga `Pengurutan`*

In [28]:
%%bigquery --project {project_id} --verbose

SELECT
    PARSE_DATE('%m/%d/%Y', o.order_date) AS tanggal_pesanan,
    COUNT(DISTINCT o.order_id) AS total_transaksi,
    SUM(od.quantity) AS total_pizza_terjual,
    SUM(od.quantity * CAST(REPLACE(p.price, 'IDR', '') AS NUMERIC)) AS total_pendapatan,
    SUM(od.quantity * (CAST(REPLACE(p.price, 'IDR', '') AS NUMERIC) - CAST(REPLACE(p.production_cost, 'IDR', '') AS NUMERIC))) AS total_keuntungan,
    SUM(CASE WHEN o.is_complain = 1 THEN 1 ELSE 0 END) AS total_komplain
FROM
    pizza_transaction.trx_order AS o
JOIN
    pizza_transaction.trx_order_detail AS od ON o.order_id = od.order_id
JOIN
    pizza_transaction.mst_pizza AS p ON od.pizza_id = p.pizza_id
GROUP BY
    tanggal_pesanan
ORDER BY
    tanggal_pesanan

Executing query with job ID: 63389fad-59b2-40c7-8c8c-8083b451abf4
Query executing: 5.51s
Job ID 722aae10-b49b-44f3-b4aa-cd8fada782a7 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

,tanggal_pesanan,total_transaksi,total_pizza_terjual,total_pendapatan,total_keuntungan,total_komplain
0,2025-01-01,69,162,21982185.000000000,4422924.000000000,26
1,2025-01-02,67,165,22128390.000000000,4496229.000000000,21
2,2025-01-03,66,158,21565440.000000000,4392873.000000000,13
3,2025-01-04,52,106,14219145.000000000,2841561.000000000,9
4,2025-01-05,54,125,16734195.000000000,3206466.000000000,19
...,...,...,...,...,...,...
353,2025-12-27,35,89,11493900.000000000,2358963.000000000,12
354,2025-12-28,39,102,13261320.000000000,2576529.000000000,13
355,2025-12-29,27,80,10961325.000000000,2200041.000000000,14
356,2025-12-30,32,82,10836180.000000000,2311983.000000000,1
357,2025-12-31,73,179,23764995.000000000,4863969.000000000,21

Kamu juga bisa melakukan analisis yang lebih komprehensif seperti :      
- Biasanya ada berapa pizza dalam satu pesanan? Apakah kita memiliki produk pizza yang paling laris (best seller)?
- Komplain apa yang paling sering terjadi? Bagaimana rencana untuk memitigasi masalah tersebut?
- Apakah ada jam-jam sibuk (peak hours)?

Atau silahkan buat pertanyaan hebatmu sendri! :D

### **Analisis: Rata-rata Pizza per Pesanan**

Untuk mengetahui berapa banyak pizza yang biasanya ada dalam satu pesanan, kita bisa menghitung rata-rata kuantitas pizza per `order_id`.

In [29]:
%%bigquery --project {project_id} --verbose

SELECT
    ROUND(AVG(total_pizza_per_order), 2) AS rata_rata_pizza_per_pesanan
FROM (
    SELECT
        o.order_id,
        SUM(od.quantity) AS total_pizza_per_order
    FROM
        pizza_transaction.trx_order AS o
    JOIN
        pizza_transaction.trx_order_detail AS od ON o.order_id = od.order_id
    GROUP BY
        o.order_id
)

Executing query with job ID: 79bc4c9e-e8d5-4c4e-9004-3da00681b737
Query executing: 0.89s
Job ID 79bc4c9e-e8d5-4c4e-9004-3da00681b737 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

   rata_rata_pizza_per_pesanan
0                         2.32

### **Analisis: Produk Pizza Terlaris (Best Seller)**

Untuk menemukan produk pizza terlaris, kita akan menghitung total kuantitas yang terjual untuk setiap tipe pizza. Ini melibatkan penggabungan tabel detail pesanan (`trx_order_detail`), informasi pizza (`mst_pizza`), dan tipe pizza (`mst_pizza_type`).

In [30]:
%%bigquery --project {project_id} --verbose

SELECT
    pt.name AS nama_pizza,
    SUM(od.quantity) AS total_kuantitas_terjual
FROM
    pizza_transaction.trx_order_detail AS od
JOIN
    pizza_transaction.mst_pizza AS p ON od.pizza_id = p.pizza_id
JOIN
    pizza_transaction.mst_pizza_type AS pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY
    nama_pizza
ORDER BY
    total_kuantitas_terjual DESC
LIMIT 5

Executing query with job ID: 791a3a75-3ab9-4765-8012-7db1d2173cbf
Query executing: 0.77s
Job ID 791a3a75-3ab9-4765-8012-7db1d2173cbf successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

                   nama_pizza  total_kuantitas_terjual
0    THE CLASSIC DELUXE PIZZA                     2453
1  THE BARBECUE CHICKEN PIZZA                     2432
2          THE HAWAIIAN PIZZA                     2424
3         THE PEPPERONI PIZZA                     2418
4      THE THAI CHICKEN PIZZA                     2371

### **Analisis: Komplain Paling Sering Terjadi**

Untuk mengidentifikasi komplain yang paling sering terjadi, kita akan menghitung jumlah kemunculan setiap jenis `complain_detail` dari tabel `trx_order` dan mengurutkannya dari yang terbanyak.

In [31]:
%%bigquery --project {project_id} --verbose

SELECT
    complain_detail,
    COUNT(*) AS jumlah_komplain
FROM
    pizza_transaction.trx_order
WHERE
    is_complain = 1 AND complain_detail IS NOT NULL
GROUP BY
    complain_detail
ORDER BY
    jumlah_komplain DESC
LIMIT 5

Executing query with job ID: 6873f35d-8137-40ba-bb35-f08cf92634e6
Query executing: 0.76s
Job ID 6873f35d-8137-40ba-bb35-f08cf92634e6 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

        complain_detail  jumlah_komplain
0      Missing toppings              528
1       Pizza was burnt              445
2   Order took too long              312
3  Received wrong pizza              288
4      Wrong pizza size              242

### **Analisis: Jam-Jam Sibuk (Peak Hours)**

Untuk mengidentifikasi jam-jam sibuk, kita akan menghitung jumlah transaksi yang terjadi pada setiap jam dalam sehari.

In [32]:
%%bigquery --project {project_id} --verbose

SELECT
    FORMAT_TIME('%H', PARSE_TIME('%H:%M:%S', order_time)) AS jam_pesanan,
    COUNT(order_id) AS jumlah_transaksi
FROM
    pizza_transaction.trx_order
GROUP BY
    jam_pesanan
ORDER BY
    jumlah_transaksi DESC
LIMIT 10

Executing query with job ID: 0c85c713-63f8-4ef3-9c6b-049e97015b20
Query executing: 0.64s
Job ID 0c85c713-63f8-4ef3-9c6b-049e97015b20 successfully executed

Query is running:   0%|          |

Downloading:   0%|          |

  jam_pesanan  jumlah_transaksi
0          12              2520
1          13              2455
2          18              2399
3          17              2336
4          19              2009
5          16              1920
6          20              1642
7          14              1472
8          15              1468
9          11              1231

# **What's Next : SQL Syntax Order!**

SQL Syntax Order adalah urutan penulisan klausul SQL yang wajib diikuti agar query valid secara sintaks. Jika urutannya salah syntax error

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-SQL/SQL%20Logical%20Order.jpg" width="60%">

Data Source : <i>https://mavenanalytics.io/data-playground/pizza-place-sales</i> (dengan modifikasi)

---

<br>
<img src="https://img.shields.io/badge/-© 2026 | Data Engineer Course FSB-417DAC?style=for-the-badge&logoColor=white"/>

<br><img src="https://fullstackbangalore.com/wp-content/uploads/2025/12/Logo-Fullstack-Bangalore.webp">